import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

/**
 * 本机 Cookie 存储（给 HTTP 详情接口 + yt-dlp 共用）。
 * 用户从已登录抖音的浏览器 DevTools 复制 Cookie 头即可。
 */

export function cookiesDataDir() {
  return path.join(
    process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming'),
    'DouyinFrames',
  );
}

export function cookieHeaderPath() {
  return path.join(cookiesDataDir(), 'cookie-header.txt');
}

export function cookieNetscapePath() {
  return (
    process.env.YT_DLP_COOKIES ||
    path.join(cookiesDataDir(), 'cookies.txt')
  );
}

export async function loadCookieHeader() {
  if (process.env.DOUYIN_COOKIES?.trim()) return process.env.DOUYIN_COOKIES.trim();
  try {
    const p = cookieHeaderPath();
    if (!fs.existsSync(p)) return '';
    return (await fsp.readFile(p, 'utf8')).trim();
  } catch {
    return '';
  }
}

/**
 * 将 `a=1; b=2` 写成 Netscape cookies.txt，供 yt-dlp --cookies 使用
 */
export function cookieHeaderToNetscape(header, domains = ['.douyin.com', '.iesdouyin.com']) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by douyin-frames. Do not edit by hand if unsure.',
  ];
  const parts = String(header || '')
    .split(';')
    .map((s) => s.trim())
    .filter(Boolean);
  for (const part of parts) {
    const eq = part.indexOf('=');
    if (eq < 1) continue;
    const name = part.slice(0, eq).trim();
    const value = part.slice(eq + 1).trim();
    if (!name || /[\s\t]/.test(name)) continue;
    for (const domain of domains) {
      // domain \t includeSub \t path \t secure \t expires \t name \t value
      lines.push(`${domain}\tTRUE\t/\tFALSE\t2147483647\t${name}\t${value}`);
    }
  }
  return `${lines.join('\n')}\n`;
}

export async function saveCookieHeader(header) {
  const text = String(header || '')
    .replace(/^cookie:\s*/i, '')
    .trim();
  const dir = cookiesDataDir();
  await fsp.mkdir(dir, { recursive: true });
  const headerFile = cookieHeaderPath();
  const netscapeFile = path.join(dir, 'cookies.txt');

  if (!text) {
    await fsp.rm(headerFile, { force: true }).catch(() => {});
    await fsp.rm(netscapeFile, { force: true }).catch(() => {});
    return { saved: false, path: netscapeFile };
  }

  await fsp.writeFile(headerFile, text, 'utf8');
  await fsp.writeFile(netscapeFile, cookieHeaderToNetscape(text), 'utf8');
  process.env.DOUYIN_COOKIES = text;
  process.env.YT_DLP_COOKIES = netscapeFile;
  return { saved: true, path: netscapeFile, length: text.length };
}

/** 启动时若已有本地 Cookie，挂到进程环境变量 */
export async function hydrateCookieEnv() {
  const header = await loadCookieHeader();
  if (header) process.env.DOUYIN_COOKIES = header;
  const ns = path.join(cookiesDataDir(), 'cookies.txt');
  if (fs.existsSync(ns)) process.env.YT_DLP_COOKIES = ns;
  return Boolean(header || fs.existsSync(ns));
}
